[build]
  # Remove `base` so Netlify works from the root directory
  command = "npm run build --prefix client"  # Builds project from the `client` folder directly
  publish = "client/build"  # Direct Netlify to find the built files in `client/build`

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
