[build]
  # Sets the directory where your frontend code is located
  base = "client"
  # Command to build the frontend project
  command = "npm run build"
  # Directory where the built files are located after the build command runs
  publish = "client/build"

  # Specify Node version if needed
  environment = { NODE_VERSION = "18" }

[[redirects]]
  # Redirects all routes to index.html for single-page applications (SPA)
  from = "/*"
  to = "/index.html"
  status = 200
