[build]
  # Set the base directory to the frontend folder
  base = "client"
  # Build command for your frontend project
  command = "npm run build"
  # Publish directory where Netlify will find the built files
  publish = "client/build"

[[redirects]]
  # Redirect all routes to index.html for single-page applications (SPA)
  from = "/*"
  to = "/index.html"
  status = 200
